version: '3.4'

services:
  bot:
    build:
      context: "./"
    volumes:
      - bot_data:/bot/data
      - bot_fake_data:/bot/fakedata
    env_file:
      - .env.production

volumes:
  bot_data:
  bot_fake_data:
